all:
	$(gcc) -o build/main.exe $(wildcard *.c)
	$(link) -llibraries ...
		$(gcc) -o build/main.exe $(wildcard *.c) debuglog.c
		# Добавить debuglog.c в сборку, если используется Makefile

clean:
	rm -rf build/*

<environment_details>

</environment_details>
</write_to_file>

<execute_command>
<command>make clean && make -f Makefile all</command>
<requires_approval>true</requires_approval>
<task_progress>
- [x] Created new project structure
- [ ] Successfully compiled project
- [ ] Tested binary execution
</task_progress>
</execute_command>

<browser_action>
<action>launch</action>
<url>file:///d:/Coding/VSCode/CLang/test1/build/main.exe</url>
<coordinate>400,300</coordinate>
</browser_action>

<environment_details>
# Visual Studio Code Visible Files
src/Makefile

# Visual Studio Code Open Tabs
main.c
src/todo.md
src/Makefile
.vscode/launch.json

# Current Time
10/4/2025, 11:22:29 PM (Europe/Moscow, UTC+3:00)

# Context Window Usage
0 / 38.992K tokens used (0%)

# Current Mode
ACT MODE
</environment_details>
